name: Full Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Backend Variables and Create .env
        run: |
          echo "Fetching backend environment variables..."
          echo "${{ vars.BACKEND_ENV }}" > backend.env
          echo "This is the content of the backend.env file:"
          cat backend.env

          echo "Fetching docker database environment variables..."
          echo "${{ vars.DATABASE_ENV }}" > database.env
          echo "This is the content of the database.env file:"
          cat database.env

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "Internship-2025/Resume-Screening-App/"

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd Internship-2025/Resume-Screening-App
            docker compose up -d db
            docker compose build backend
            docker compose up -d --force-recreate backend
            docker system prune -af

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Frontend Variables and Create .env
        run: |
          echo "Fetching frontend environment variables..."
          echo "${{ vars.FRONTEND_ENV }}" > frontend.env
          echo "${{ vars.FRONTEND_ENV }}" > Frontend/.env
          echo "This is the content of the frontend.env file:"
          cat frontend.env

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "Internship-2025/Resume-Screening-App/"

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd Internship-2025/Resume-Screening-App
            docker compose build frontend
            docker compose up -d --force-recreate frontend
            docker system prune -af 

            
